"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.transformToNumber = exports.transformToBoolean = exports.transformToArray = exports.convertDTOToSearchQuery = exports.UserRoles = exports.VariableGroupType = exports.OrderStatus = exports.PromocodeTypes = exports.SizeTableEnum = exports.GetCartResponse = exports.Profile = exports.CartItem = exports.GetProductGroupRequest = exports.GetProductRequest = exports.Collection = exports.VariableGroup = exports.Variable = exports.Product = exports.PartialProduct = exports.Order = exports.ChatMessage = exports.CustomerData = exports.PartialOrder = exports.OrderHistory = exports.PricePromocode = exports.PartnerPromocode = exports.DiscountPromocode = exports.BasePromocode = exports.News = exports.File = exports.PartialDocument = exports.AuthProfileId = exports.AuthVerify = exports.AuthTelegram = exports.AuthPhone = void 0;
var auth_1 = require("./dtos/auth");
Object.defineProperty(exports, "AuthPhone", { enumerable: true, get: function () { return auth_1.AuthPhone; } });
Object.defineProperty(exports, "AuthTelegram", { enumerable: true, get: function () { return auth_1.AuthTelegram; } });
Object.defineProperty(exports, "AuthVerify", { enumerable: true, get: function () { return auth_1.AuthVerify; } });
Object.defineProperty(exports, "AuthProfileId", { enumerable: true, get: function () { return auth_1.AuthProfileId; } });
var common_1 = require("./dtos/common");
Object.defineProperty(exports, "PartialDocument", { enumerable: true, get: function () { return common_1.PartialDocument; } });
var files_1 = require("./dtos/files");
Object.defineProperty(exports, "File", { enumerable: true, get: function () { return files_1.File; } });
var news_1 = require("./dtos/news");
Object.defineProperty(exports, "News", { enumerable: true, get: function () { return news_1.News; } });
var order_1 = require("./dtos/order");
Object.defineProperty(exports, "BasePromocode", { enumerable: true, get: function () { return order_1.BasePromocode; } });
Object.defineProperty(exports, "DiscountPromocode", { enumerable: true, get: function () { return order_1.DiscountPromocode; } });
Object.defineProperty(exports, "PartnerPromocode", { enumerable: true, get: function () { return order_1.PartnerPromocode; } });
Object.defineProperty(exports, "PricePromocode", { enumerable: true, get: function () { return order_1.PricePromocode; } });
Object.defineProperty(exports, "OrderHistory", { enumerable: true, get: function () { return order_1.OrderHistory; } });
Object.defineProperty(exports, "PartialOrder", { enumerable: true, get: function () { return order_1.PartialOrder; } });
Object.defineProperty(exports, "CustomerData", { enumerable: true, get: function () { return order_1.CustomerData; } });
Object.defineProperty(exports, "ChatMessage", { enumerable: true, get: function () { return order_1.ChatMessage; } });
Object.defineProperty(exports, "Order", { enumerable: true, get: function () { return order_1.Order; } });
var product_1 = require("./dtos/product");
Object.defineProperty(exports, "PartialProduct", { enumerable: true, get: function () { return product_1.PartialProduct; } });
Object.defineProperty(exports, "Product", { enumerable: true, get: function () { return product_1.Product; } });
Object.defineProperty(exports, "Variable", { enumerable: true, get: function () { return product_1.Variable; } });
Object.defineProperty(exports, "VariableGroup", { enumerable: true, get: function () { return product_1.VariableGroup; } });
Object.defineProperty(exports, "Collection", { enumerable: true, get: function () { return product_1.Collection; } });
Object.defineProperty(exports, "GetProductRequest", { enumerable: true, get: function () { return product_1.GetProductRequest; } });
Object.defineProperty(exports, "GetProductGroupRequest", { enumerable: true, get: function () { return product_1.GetProductGroupRequest; } });
var profile_1 = require("./dtos/profile");
Object.defineProperty(exports, "CartItem", { enumerable: true, get: function () { return profile_1.CartItem; } });
Object.defineProperty(exports, "Profile", { enumerable: true, get: function () { return profile_1.Profile; } });
Object.defineProperty(exports, "GetCartResponse", { enumerable: true, get: function () { return profile_1.GetCartResponse; } });
var files_2 = require("./enums/files");
Object.defineProperty(exports, "SizeTableEnum", { enumerable: true, get: function () { return files_2.SizeTableEnum; } });
var order_2 = require("./enums/order");
Object.defineProperty(exports, "PromocodeTypes", { enumerable: true, get: function () { return order_2.PromocodeTypes; } });
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return order_2.OrderStatus; } });
var product_2 = require("./enums/product");
Object.defineProperty(exports, "VariableGroupType", { enumerable: true, get: function () { return product_2.VariableGroupType; } });
var profile_2 = require("./enums/profile");
Object.defineProperty(exports, "UserRoles", { enumerable: true, get: function () { return profile_2.UserRoles; } });
var query_1 = require("./functions/query");
Object.defineProperty(exports, "convertDTOToSearchQuery", { enumerable: true, get: function () { return query_1.convertDTOToSearchQuery; } });
Object.defineProperty(exports, "transformToArray", { enumerable: true, get: function () { return query_1.transformToArray; } });
Object.defineProperty(exports, "transformToBoolean", { enumerable: true, get: function () { return query_1.transformToBoolean; } });
Object.defineProperty(exports, "transformToNumber", { enumerable: true, get: function () { return query_1.transformToNumber; } });
//# sourceMappingURL=index.js.map